import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import HomeHero from '@/components/HomeHero'
import HomeSectionTwo from '@/components/HomeSectionTwo'
import HomeSectionThree from '@/components/HomeSectionThree'
import HomeSectionFour from '@/components/HomeSectionFour'
import HomeSectionFive from '@/components/HomeSectionFive'
import FAQ from '@/components/FAQ'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>NetFlix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <HomeHero/>
       <HomeSectionTwo/>
       <HomeSectionThree/>
       <HomeSectionFour/>
       <HomeSectionFive/>
       <FAQ/>
       <div className='border-t-8 border-netflixGray '></div>
       <Footer/>
      </main>
    </>
  )
}
